<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="HomePage.aspx.cs" Inherits="GridViewCRUD_Demo.HomePage" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <div style="margin-left: auto; margin-right: auto; padding-top: 20px;">
        <h1 style="text-align: center">Add Employee</h1>
        <form id="form1" runat="server">
            <table style="margin-left: auto; margin-right: auto; padding-top: 20px;">
                <tr>
                    <td>
                        <asp:Label ID="lblName" runat="server" Text="Name"></asp:Label>
                    </td>
                    <td>
                        <asp:TextBox ID="txtName" runat="server" PlaceHolder="Enter Name"></asp:TextBox>

                        <asp:RequiredFieldValidator ID="rfvName" runat="server" ErrorMessage="Name is Required"
                            Text="*" ForeColor="Red" ControlToValidate="txtName" Display="Dynamic" Font-Bold="true"></asp:RequiredFieldValidator>
                    </td>
                </tr>
                <tr>
                    <td>
                        <asp:Label ID="lblEmail" runat="server" Text="Email"></asp:Label>
                    </td>
                    <td>
                        <asp:TextBox ID="txtEmail" runat="server" PlaceHolder="Enter Email"></asp:TextBox>

                        <asp:RequiredFieldValidator ID="rvfEmail" runat="server" ErrorMessage="Email is Required"
                            Text="*" ForeColor="Red" ControlToValidate="txtEmail" Display="Dynamic" Font-Bold="true"></asp:RequiredFieldValidator>
                        <asp:RegularExpressionValidator ID="rgEmail" runat="server" ErrorMessage="Invalid Email"
                            Text="*" ForeColor="Red" ControlToValidate="txtEmail" Display="Dynamic" Font-Bold="true" ValidationExpression="\w+([-+.']\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*"></asp:RegularExpressionValidator>
                    </td>
                </tr>
                <tr>
                    <td>
                        <asp:Label ID="lblSalary" runat="server" Text="Salary"></asp:Label>
                    </td>
                    <td>
                        <asp:TextBox ID="txtSalary" runat="server" PlaceHolder="Enter Salary"></asp:TextBox>

                        <asp:RequiredFieldValidator ID="rvfSalary" runat="server" ErrorMessage="Salary is Required"
                            Text="*" ForeColor="Red" ControlToValidate="txtSalary" Display="Dynamic" Font-Bold="true"></asp:RequiredFieldValidator>
                        <asp:RangeValidator ID="rgSalary" runat="server" ErrorMessage="Salary between 1k-1L" MinimumValue="1000" MaximumValue="100000"
                            Type="Integer" Text="I" ForeColor="Red" ControlToValidate="txtSalary" Display="Dynamic" Font-Bold="true"></asp:RangeValidator>
                    </td>
                </tr>
                <br />
                <tr>
                    <td colspan="2" style="text-align: center">
                        <asp:Button ID="btnAddEmployee" runat="server" Text="Add Employee" OnClick="btnAddEmployee_Click" />
                    </td>
                </tr>
                <tr>
                    <td colspan="2" style="text-align: center">
                        <asp:Label ID="lblMessage" runat="server" Text=""></asp:Label>
                    </td>
                </tr>
                <br />
                <tr>
                    <td colspan="2" style="text-align: center">
                        <asp:ValidationSummary ID="ValidationSummary1" ShowValidationErrors="true"
                            HeaderText="Form Errors" ShowMessageBox="true" ShowSummary="true" ForeColor="Red" Font-Bold="true" runat="server" />
                    </td>
                </tr>
            </table>
            <table style="margin-left: auto; margin-right: auto; padding-top: 20px;">
                <tr>
                    <td>
                        <asp:GridView ID="grData" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" OnRowCancelingEdit="grData_RowCancelingEdit" OnRowDeleting="grData_RowDeleting" OnRowEditing="grData_RowEditing" OnRowUpdating="grData_RowUpdating">
                            <Columns>
                                <asp:TemplateField Visible="false">
                                    <HeaderTemplate>
                                        <asp:Label ID="lblIdHeader" runat="server" Text="ID"></asp:Label>
                                    </HeaderTemplate>
                                    <ItemTemplate>
                                        <asp:Label ID="lblIdItem" runat="server" Text='<%#Eval("Id") %>'></asp:Label>
                                    </ItemTemplate>
                                    <EditItemTemplate>
                                        <asp:Label ID="lblIdEdit" runat="server" Text='<%#Eval("Id") %>'></asp:Label>
                                    </EditItemTemplate>
                                </asp:TemplateField>

                                <asp:TemplateField>
                                    <HeaderTemplate>
                                        <asp:Label ID="lblNameHeader" runat="server" Text="Name"></asp:Label>
                                    </HeaderTemplate>
                                    <ItemTemplate>
                                        <asp:Label ID="lblNameItem" runat="server" Text='<%#Eval("Name") %>'></asp:Label>
                                    </ItemTemplate>
                                    <EditItemTemplate>
                                        <asp:TextBox ID="txtNameEdit" runat="server" Text='<%#Eval("Name") %>'></asp:TextBox>
                                    </EditItemTemplate>
                                </asp:TemplateField>

                                <asp:TemplateField>
                                    <HeaderTemplate>
                                        <asp:Label ID="lblEmailHeader" runat="server" Text="Email"></asp:Label>
                                    </HeaderTemplate>
                                    <ItemTemplate>
                                        <asp:Label ID="lblEmailItem" runat="server" Text='<%#Eval("Email") %>'></asp:Label>
                                    </ItemTemplate>
                                    <EditItemTemplate>
                                        <asp:TextBox ID="txtEmailEdit" runat="server" Text='<%#Eval("Email") %>'></asp:TextBox>
                                    </EditItemTemplate>
                                </asp:TemplateField>

                                <asp:TemplateField>
                                    <HeaderTemplate>
                                        <asp:Label ID="lblSalaryHeader" runat="server" Text="Email"></asp:Label>
                                    </HeaderTemplate>
                                    <ItemTemplate>
                                        <asp:Label ID="lblSlaryItem" runat="server" Text='<%#Eval("Salary") %>'></asp:Label>
                                    </ItemTemplate>
                                    <EditItemTemplate>
                                        <asp:TextBox ID="txtSalaryEdit" runat="server" Text='<%#Eval("Salary") %>'></asp:TextBox>
                                    </EditItemTemplate>
                                </asp:TemplateField>

                            </Columns>

                        </asp:GridView>
                    </td>
                </tr>
                <tr>
                    <td>
                        <asp:Label ID="lblGridMessage" runat="server" Text=""></asp:Label>
                    </td>
                </tr>
            </table>
        </form>
    </div>
</body>
</html>
