//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoringImage_CRUD_Udemy.Models.DataBaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProd_Img
    {
        public int Id { get; set; }
        public string ProdId { get; set; }
        public string ProdName { get; set; }
        public int ProdQty { get; set; }
        public decimal ProdPrice { get; set; }
        public string Image { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}
