<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Home.aspx.cs" Inherits="AuthenticationDemo.Home" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
        <div style="margin-left: auto; margin-right: auto; padding-top: 15px;">
            <h3 runat="server" id="h3Content" style="text-align: left; padding-left: 20px; color: brown">Welcome, </h3>
            <p style="text-align: left; padding-left: 20px; color: orangered">
                <asp:LinkButton ID="linkLogout" runat="server" OnClick="linkLogout_Click">LogOut</asp:LinkButton>
            </p>
            <table style="margin-left: auto; margin-right: auto; padding-top: 15px; border: dotted; align-content: center;">
                <tr>
                    <td>
                        <asp:GridView ID="grUserData" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" BackColor="#DEBA84" BorderColor="#DEBA84" BorderStyle="None" BorderWidth="1px" CellPadding="3" CellSpacing="2" OnRowCancelingEdit="grUserData_RowCancelingEdit" OnRowDeleting="grUserData_RowDeleting" OnRowEditing="grUserData_RowEditing" OnRowUpdating="grUserData_RowUpdating">
                            <Columns>
                                <asp:TemplateField HeaderText ="Name">
                                    <%--<HeaderTemplate>
                                        <asp:Label ID="lblNameHeader" runat="server" Text="Name"></asp:Label>
                                    </HeaderTemplate>--%>

                                    <ItemTemplate>
                                        <asp:Label ID="lblNameItem" runat="server" Text='<%#Eval("Name") %>'></asp:Label>
                                    </ItemTemplate>
                                    <EditItemTemplate>
                                        <asp:TextBox ID="txtNameEdit"  runat="server" Text='<%#Eval("Name") %>' ></asp:TextBox>
                                    </EditItemTemplate>
                                    
                                </asp:TemplateField>
                                
                                <asp:TemplateField HeaderText ="Email Id">
                                    <%--<HeaderTemplate>
                                        <asp:Label ID="lblEmailHeader" runat="server" Text="Email Id"></asp:Label>
                                    </HeaderTemplate>--%>

                                    <ItemTemplate>
                                        <asp:Label ID="lblEmailItem" runat="server" Text='<%#Eval("Email") %>'></asp:Label>
                                    </ItemTemplate>
                                    <EditItemTemplate>
                                        <asp:Label ID="lblEmailEdit" runat="server" Text='<%#Eval("Email") %>' ></asp:Label>
                                    </EditItemTemplate>
                                </asp:TemplateField>
                                
                                <asp:TemplateField HeaderText="Registered Date">
                                    <%--<HeaderTemplate>
                                        <asp:Label ID="lblDateHeader" runat="server" Text="Registered Date"></asp:Label>
                                    </HeaderTemplate>
                                    --%>
                                    <ItemTemplate>
                                        <asp:Label ID="lblDateItem" runat="server" Text='<%#Eval("RegiDateTime") %>'></asp:Label>
                                    </ItemTemplate>
                                    <EditItemTemplate>
                                        <asp:Label ID="lblDateEdit" runat="server" Text='<%#Eval("RegiDateTime") %>'></asp:Label>
                                    </EditItemTemplate>
                                </asp:TemplateField>
                               
                            </Columns>
                            <FooterStyle BackColor="#F7DFB5" ForeColor="#8C4510" />
                            <HeaderStyle BackColor="#A55129" Font-Bold="True" ForeColor="White" />
                            <PagerStyle ForeColor="#8C4510" HorizontalAlign="Center" />
                            <RowStyle BackColor="#FFF7E7" ForeColor="#8C4510" />
                            <SelectedRowStyle BackColor="#738A9C" Font-Bold="True" ForeColor="White" />
                            <SortedAscendingCellStyle BackColor="#FFF1D4" />
                            <SortedAscendingHeaderStyle BackColor="#B95C30" />
                            <SortedDescendingCellStyle BackColor="#F1E5CE" />
                            <SortedDescendingHeaderStyle BackColor="#93451F" />
                        </asp:GridView>
                    </td>
                </tr>
                <tr>
                    <td style="text-align:center;font-size:large;font-style:oblique;font-weight:500">
                        <asp:Label ID="lblMessage" runat="server" Text=""></asp:Label>
                    </td>
                </tr>
            </table>
        </div>
    </form>
</body>
</html>
